logging.level:
  org.springframework.boot.web: WARN
  org.springframework.boot.context: WARN
  org.springframework.web: WARN
  org.springframework.orm: WARN
  org.springframework.core: WARN
  org.springframework.jmx: WARN
  org.hibernate: WARN
  org.apache.catalina: WARN
  org.flywaydb: DEBUG


    

spring:  
  flyway:
    sql-migration-prefix: V

  
  h2:
    console:
      enabled: true
        
  datasource:
    url: jdbc:h2:mem:emp;MODE=PostgreSQL
    password: 
    username: sa
  
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      generate-ddl: false
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: none
        
        
