apiVersion: v1
kind: Namespace
metadata:
  name: database

---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: database
spec:
  type: NodePort
  selector:
    app: database
  ports:
  - protocol: TCP
    port: 1521
    targetPort: 1521
    name: tcp
  - port: 81
    nodePort: 30003
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: database
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: h2-db
        image: h2:latest
        ports:
        - containerPort: 1521
        - containerPort: 81
        env:
          - name: H2_OPTIONS
            value: -ifNotExists 
          - name: MODE
            value: PostgreSQL
        
